# Generated by Django 5.0.6 on 2024-06-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=None, max_length=50, unique=True)),
                ('code', models.IntegerField(default=None, unique=True)),
                ('hod_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='Student_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(default='student', max_length=100)),
                ('stu_email', models.EmailField(default=None, max_length=254, unique=True)),
                ('stu_address', models.CharField(default=None, max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='studentcard.department')),
                ('stu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentId', to='studentcard.student_id')),
            ],
            options={
                'ordering': ['stu_name'],
            },
        ),
    ]
