# Generated by Django 5.0.6 on 2024-06-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default=None, max_length=70)),
                ('sub_code', models.CharField(default=None, max_length=10, unique=True)),
            ],
            options={
                'ordering': ['sub_name'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentName', to='studentcard.student')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectName', to='studentcard.subject')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
