# Generated by Django 5.0.6 on 2024-06-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcard', '0003_alter_marks_marks_alter_marks_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectDept', to='studentcard.department'),
        ),
    ]
