# Generated by Django 5.0.6 on 2024-06-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcard', '0004_subject_sub_dept'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userauth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_id',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userauth_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
