# Generated by Django 5.0.6 on 2024-06-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcard', '0005_department_user_student_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_guardian_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_pincode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
